// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axarouxelvazgeewnakv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4YXJvdXhlbHZhemdlZXduYWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDEwNDUsImV4cCI6MjA2NjUxNzA0NX0.BfKt54TsX3dD3qURMd7zBE6ycYSpw2des-SPTzC-ht8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);